name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: DATABASE_URL=postgres://postgres@localhost/postgres
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: rustfmt
        run: cargo fmt -- --check

      - name: SQLx
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: DB
        run: sqlx database create && sqlx migrate run
        
      - name: clippy
        run: cargo clippy -- -D warnings && cargo clippy --tests -- -D warnings
        
      - name: test
        run: cargo test
